src/conversions.jl
src/types.jl

I noticed these while looking into ambiguity warnings on julia 0.3.
Those are julia bugs, and since 0.4 is near let's just live with them.

Somewhat more careful conversions

---

src/ColorTypes.jl

After doing a Pkg.update() I ran into problem running PyPlot, see  https://github.com/stevengj/PyPlot.jl/issues/169
I pinned it down to ColorTypes.jl 
```julia
using ColorTypes
```
```
ERROR: @doc not defined
in include at ./boot.jl:245
in include_from_node1 at ./loading.jl:128
in reload_path at loading.jl:152
in _require at loading.jl:67
in require at loading.jl:51
while loading /home/elbeltagy/.julia/ColorTypes/src/ColorTypes.jl, in expression starting on line 86
```
This changed fixed it.

Making the @doc macro work

---

src/conversions.jl
src/traits.jl
src/types.jl
test/runtests.jl

`Bool` also makes sense as a `Gray`, so let's support that.
This also substantially generalizes `ccolor`, which is a core trait-method for generating a concrete type from underspecified types. Once tagged, this should fix the error described in https://github.com/JuliaIO/ImageMagick.jl/pull/34, CC @yuyichao.

Add support for Gray{Bool} and generalize ccolor

---

src/types.jl
test/runtests.jl

Fixes an error noticed in https://github.com/timholy/Images.jl/pull/516, by restricting a particular constructor  to `Real` arguments.

Avoid StackOverflowError on Gray(g::Gray)

---

src/ColorTypes.jl
src/traits.jl

This doesn't have any impact on 0.4, but it makes a few things a little faster with Julia 0.5.

Speed up supertype operations using atsign-pure

---

test/runtests.jl

https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/48 caught an error in the tests in this package. CC @Evizero. (That result must have seemed strange to you! Sorry I didn't catch it in my review.)

Correct InexactError in tests due to FPN widening

---

src/ColorTypes.jl
src/operations.jl
test/runtests.jl

This PR allows you to take the "elementwise max" over two RGBs:
```jl
mapc(max, rgb1, rgb2) -> rgbmax
```

Add mapc for mapping functions elementwise over color channels

---

.travis.yml
src/conversions.jl
src/types.jl
test/runtests.jl

I'm making a big push to make Images more newbie-friendly, and color handling is an important part of that. While at least some of us really like the fact that all (gray and RGB) color components lie in the range of 0 to 1, it's a perennial source of confusion for newbies. In https://github.com/JuliaMath/FixedPointNumbers.jl/pull/53 I added informative errors for conversion to fixed point, but I think it can be even nicer if we throw customized error messages here.
For example, the `InexactError` in https://github.com/JuliaGraphics/Colors.jl/issues/252 is now replaced with this:
```jl
julia> RGBA(56, 34, 23)
ERROR: ArgumentError: (56,34,23,1) are integers in the range 0-255, but integer inputs are encoded with the UFixed8
type, an 8-bit type representing 256 discrete values between 0 and …
```

Throw informative errors for illegal construction

---

src/ColorTypes.jl
src/conversions.jl
test/runtests.jl

These were missed in the previous deprecations

Add RGB24[::UInt32...] deprecations

---

src/traits.jl
test/runtests.jl

On `master` we currently have this:
```jl
julia> using ColorTypes
julia> a = Gray[0.0]
1-element Array{ColorTypes.Gray,1}:
Gray{Float64}(0.0)
julia> eltype(a)
ColorTypes.Gray{T<:Union{AbstractFloat,Bool,FixedPointNumbers.FixedPoint}}
```
Note that this is a container with abstract eltype. That's not ideal, and we should probably change it so that `Gray[0.0]` returns an array of concrete eltype. However, since it's possible to construct such an array directly with `a = Array{Gray}(1)`, the following bug still needs fixing:
```jl
julia> a[1] = 1
ERROR: MethodError: no method matching ccolor(::Type{ColorTypes.Gray}, ::Type{Int64})
Closest candidates are:
ccolor{Cdest<:ColorTypes.Colorant{T,N},Csrc<:ColorTypes.Colorant{T,N}}(::Type{Cdest<:ColorTypes.Colorant}, …
```

Do something sensible for `ccolor(Gray, Int)`

---

src/operations.jl
test/runtests.jl

This is (sort of) the other half of #59. On master we had this:
```jl
julia> b = Gray.(rand(3))
3-element Array{ColorTypes.Gray,1}:
Gray{Float64}(0.914404)
Gray{Float64}(0.682291)
Gray{Float64}(0.530828)
julia> eltype(b)
ColorTypes.Gray{T<:Union{AbstractFloat,Bool,FixedPointNumbers.FixedPoint}}
```
i.e., an abstract eltype, even though the input has concrete eltype (`Float64`). This PR makes the return eltype `Gray{Float64}`.
In #59 I pointed out that `Gray[0.1]` constructs an array of abstract eltype, and proposed that we should fix it. I now think that's probably wrong. The reasons are:
- it's easy to get a concrete eltype, just say `Gray{Float64}[0.1]` (or whatever eltype you want, it will be converted)
- if we change it, then it will be awkward to create an array of abstract eltype …

Make `Gray.(a)` return a container with concrete type (if appropriate)

---

src/traits.jl
test/runtests.jl

In the context of `red(c)`, `green(c)`, and `blue(c)` for extracting the color channels of an RGB color `c`, the definition `gray(g)` to extract the value of a Gray color `g` makes sense. However, in isolation it is sometimes a bit weird: for example, if you want to get the `Float64` value that corresponds to grayscale for an RGB color,
```jl
julia> c = RGB(0.1, 0.2, 0.3)
RGB{Float64}(0.1,0.2,0.3)
julia> Gray(c)
Gray{Float64}(0.18150000199675562)
julia> gray(Gray(c))
0.18150000199675562
```
that `gray` seems somehow less natural than
```jl
julia> real(Gray(c))
0.18150000199675562
```
This PR allows either.

Allow real(::Gray) as a synonym for gray(::Gray)

---

src/ColorTypes.jl
src/operations.jl
test/runtests.jl

it was hard coded for UFixed8/16 before, now is more general.
it's also a lot simpler, except the hack around https://github.com/JuliaLang/julia/issues/10140, which i'm not sure will add a lot of overhead or not.

refactor rand to handle arrays of UFixed{UInt16,14} and friends

---

src/traits.jl

Not sure how useful `one(Gray)` or `one(Gray{T} where T <: Fractional)` actually is but at least this solves the ambiguity error in ColorVectorSpace test.

Move one/zero from ColorVectorSpace

---

src/operations.jl
src/types.jl

When visualizing big images I noticed several performance bottlenecks. This fixes some particularly important ones; in combination with changes in other packages (which I think are less important), in certain circumstances it's more than a 10-fold speedup. EDIT: the large magnitude depended on an inference failure triggered by https://github.com/JuliaMath/FixedPointNumbers.jl/pull/80 (which is presumably a bug in julia). It's still a speedup, though.

Several performance enhancements

---

src/ColorTypes.jl
src/operations.jl
test/runtests.jl

These are the reduction analogs of `mapc`. Among other uses, this should allow simplification of certain functions in ColorVectorSpace (ref https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/72).

Add reducec and mapreducec

---

src/operations.jl
test/runtests.jl

Since we treat Numbers as a form of grayscale elsewhere, this seems to make sense. But I'd be interested in finding out whether others agree.

Define mapc, reducec, and mapreducec for Numbers

---

src/types.jl
test/runtests.jl

Fixes #80 (CC @rdeits).
This also happens to fix a weird issue I've noticed for a long time: that the tests pass when you say `using ColorTypes` (which precompiles the module), but not if you say `include("../src/ColorTypes.jl"); include("runtests.jl")`. Satisfying to have that gone.

Use controlled promotion of field inputs in constructors

---

src/ColorTypes.jl
src/operations.jl
src/traits.jl
src/types.jl
test/runtests.jl

This also modifies the implementation of a non-exported function for use in Colors

Switch to oneunit where appropriate

---

src/ColorTypes.jl
src/traits.jl
src/types.jl
test/runtests.jl

I was planning to add this to Colors, but it actually seems to make the most sense here.
Also removes some cruft due to `UnionAll` checks.

Define isapprox and remove cruft

---

src/traits.jl
test/runtests.jl

This fixes a test failure in Images.

Don't require precise type-equality for isapprox

---

README.md
src/ColorTypes.jl
src/conversions.jl
src/operations.jl
src/types.jl
test/runtests.jl

As a PR this is a grab-bag, but each commit makes sense on its own.
- Formerly, `AGray{Float64}(GrayA(0.1, 0.2))` was throwing a depwarn about constructors no longer falling back to `convert`
- We were still using `U8` in the README! :confounded: 
- `rand` now returns an `Array` rather than a `ReinterpretedArray` (it does the reinterpreting internally)

Fixes needed for ImageCore

---

src/ColorTypes.jl
src/types.jl
test/runtests.jl

This PR exports missing types used in other packages of the Images.jl project. I appreciate if you can review and merge. I will submit another PR to Colors.jl and Images.jl meanwhile.

Export types used in other packages of the Images.jl project

---

src/ColorTypes.jl
src/traits.jl
test/runtests.jl

This patch is a generalization of https://github.com/JuliaImages/Images.jl/issues/803#issuecomment-488139972
Expanding the existing `FixedPointNumbers.floattype` seems reasonable to me, but if there are concerns on type piracy, I'm also happy to use a new name.
Blocking PR:

expand floattype from FixedPointNumbers

---

src/types.jl
test/runtests.jl

e.g. alphacolor(RGBA) == ARGB, coloralpha(ARGB) == ARGB
This helps the conversion from `AlphaColor` to `ColorAlpha` or vice versa. (fixes #126)

Add support for "Type" input of `TransparentColor` to `alphacolor`/`coloralpha` (#126)

---

src/ColorTypes.jl
src/traits.jl
test/runtests.jl

This adds and exports two functions for (mainly) Lab-like colors (cf. #134).

Add `chroma()` and `hue()` (#134)

---

src/ColorTypes.jl
src/operations.jl
src/precompile.jl

This adds some precompile statements to reduce latency. Because the methods are simple to infer, the savings are modest, but combined with precompiles in other packages (FixedPointNumbers, Colors, ColorVectorSpace) I'm getting latency reductions of ~30% for some common operations. So these seem worth having.

Add some precompiles

---

Project.toml
README.md
src/ColorTypes.jl
src/traits.jl
src/types.jl
test/runtests.jl

I realized we should do this sooner than later, to give other packages time to deal with deprecation warnings. When we release 1.0 we should eliminate the deprecations.

Rename RGB1->XRGB, RGB4->RGBX

---

Project.toml
src/ColorTypes.jl

I decided to add this workaround simply because it has already been added to FixedPointNumbers.jl and Colors.jl.
Until a specific problem with precompilation is discovered, the backporting to v0.8 (ie creating a branch) is pending.

Work around JuliaLang/julia#34121 and Release 0.9.1

---

src/ColorTypes.jl
src/types.jl
test/runtests.jl

cf. https://github.com/JuliaGraphics/Colors.jl/issues/273#issuecomment-557839812
This also adds new type aliases `AbstractARGB`/`AbstractRGBA` for the consistency. (This does not add `AlphaColor3`/`ColorAlpha3`, though.)
`ARGB32` and `AGray32` are now defined with the new type aliases.

[RFC] Move type aliases `AbstractAGray`/`AbstractGrayA` from Colors.jl

---

src/conversions.jl
test/conversions.jl

~This is a draft PR for issue #144. (This depends on PR #146.)~ PR #146 was merged.
This moves the promotion rules with grays and rgbs from Colors.jl.(Closes #144)
This also adds the gray-to-rgb conversion methods.
The current promotion rules have some problems, but this does not fix them since this focuses on the migration.

Move promotion rules from Colors.jl and Add gray-to-rgb conversion methods

---

src/ColorTypes.jl
src/traits.jl
src/types.jl
test/conversions.jl
test/traits.jl

This does some maintenance on the type system of ColorTypes. In particular it leverages the huge improvements in Julia's type system and optimizer that allow one to write the code in block form rather than large dispatch chains. This makes it somewhat easier to perform complex logic. It fixes quite a few of our `@test_broken`s, though there are others that should be investigated.
With respect to upstream tests, the most breaking part of this might be the introduction of `TwoColorTypeError`; I can revert that and go back to `ErrorException` if there's a clear consensus against it. But I introduced it to improve printing of error messages for the user.
I have some additional tests I wrote, but they are partly redundant with what we already have. Therefore I'm posting them in a …

Improve implementation of ccolor

---

src/traits.jl
test/traits.jl

This allows:
- `color_type` and `base_color_type` to accept `Colorant` inputs
- `color_type` and `base_colorant_type` to accept `Number` inputs
- `base_colorant_type` to handle the abstract transparent types without `N`
(closes #168)

Improve `color_type`, `base_color_type` and `base_colorant_type` (Fixes #168)

---

src/conversions.jl
test/conversions.jl

This PR is an alternative solution of PR #164.
The notable difference is that the rules implemented in this PR promote `AlphaColor` and `ColorAlpha` to `AlphaColor` instead of `TransparentColor`. (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/129#issuecomment-589990753)

[Alternative] Improve promotion rules (Fixes #129)

---

src/conversions.jl
src/traits.jl
src/types.jl
test/conversions.jl
test/traits.jl

This fixes #163.
This PR also moves `real` and `reinterpret` to "conversions.jl", and removes the methods which were once needed due to ambiguity.

Fix RGB24/ARGB32 conversions (Fixes #163)

---

src/traits.jl
test/traits.jl

It's required by JuliaImages/ImageMorphology.jl#24 to support MaxTree-based operations in grayscale images.

add isless(a::AbstractGray, b::AbstractGray)

---

src/show.jl
src/traits.jl
test/show.jl
test/traits.jl

This fixes #151, but does not change `eltype(C)` for the backward compatibility.
This also moves `colorant_string` and `colorant_string_with_eltype` to "show.jl".

Fix display of strange element types within `colorant_string_with_eltype`

---

src/ColorTypes.jl
src/error_hints.jl
test/error_hints.jl
test/runtests.jl

This gives a user-friendly error message when ColorVectorSpace isn't loaded.
```julia
julia> zero(RGB)
ERROR: MethodError: no method matching zero(::Type{RGB})
did you forget to `using ColorVectorSpace`?
Closest candidates are:
...
julia> zero(RGB(1, 1, 1))
ERROR: MethodError: no method matching zero(::RGB{FixedPointNumbers.Normed{UInt8,8}})
did you forget to `using ColorVectorSpace`?
Closest candidates are:
...
```

add custom error hints for zero and one to ColorVectorSpace

---

.travis.yml
src/traits.jl
test/Project.toml
test/conversions.jl
test/operations.jl
test/runtests.jl
test/show.jl
test/traits.jl
test/types.jl

This makes them standalone, which is necessary for juliaimages docs. Alternatively we could use the same `setdocmeta!` statement there, but this seems to have lower overhead for any other package that might want to incorporate these docs.

Add setup block to doctests

---

Project.toml
src/ColorTypes.jl
src/error_hints.jl

#178 is buggy (see https://github.com/JuliaGraphics/ColorTypes.jl/pull/178#issuecomment-614902798), this PR fixes that
Bump a version because it already breaks CI for downstream packages, e.g., https://github.com/JuliaGraphics/ColorSchemes.jl/pull/33, https://github.com/JuliaImages/Images.jl/runs/593248480
~To make sure this kind of issue doesn't happen again, I also added Colors and ImageCore tests in CI.~

fixes a precompilation error when registering error hints

---

src/error_hints.jl
test/runtests.jl

Fixes #192. The strategy used here has the advantage of being safer against future changes.

Fix on nightly

---

src/ColorTypes.jl
src/conversions.jl

Ref https://github.com/JuliaLang/julia/pull/35733. This will have very little impact on its own, but it shouldn't hurt anything and it prepares the way for future gains.
Based on #193 and local tests I expect this to crash on 1.4, so for now this is mostly posted as a reference for a bug report.

Reduce invalidations of other methods

---

Project.toml
test/conversions.jl
test/types.jl

We are going to support `alpha(::Number)` (cf. PR #177).
This adds tests for the 1-arg rgb/transparent-rgb constructors. Some broken tests should be fixed by PR #177.
I'm concerned about supporting 2-arg transparent rgb construcctors. The 2-arg constructors are not the abbreviations for the 3-arg/4-arg constructors.
```julia
julia> ARGB(Gray(1), 0.5)
ARGB{N0f8}(1.0,1.0,1.0,0.502)
julia> ARGB(1, 0.5) # Is this needed?
ERROR: MethodError: no method matching ARGB(::Int64, ::Float64)
```

Add tests for 1-arg rgb constructors

---

README.md
src/ColorTypes.jl
src/operations.jl
src/traits.jl
test/operations.jl
test/traits.jl

This is a modified version of part of PR #189, but this does not change the `show()`.
In the future, I want to be able to get an iterator or tuple of the components (cf. #190, https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/131#discussion_r443177446).

Add component accessor `comp4`/`comp5`

---

src/show.jl
src/traits.jl
test/show.jl
test/traits.jl

This is the successor to #198 and the rest of PR #189, but the bug fix for `show(::AGray32)` is removed.

Generalize `show` for colors with uncommon components

---

Project.toml
src/traits.jl

Fixes #208
This reimplements the function, although the implementation still depends on non-public APIs (i.e. `Base.unwrap_unionall` and `Base.rewrap_unionall`).
This also generalizes `eltypes_supported` for non-parametric color types.
We haven't merged the breaking changes yet, so I plan to release v0.10.7.

Reimplement `parameter_upper_bound`

---

Project.toml
src/show.jl
test/show.jl

In PR #174 (v0.10.0), the module names were displayed for invisible non-concrete types. In PR #199, non-parametric types also joined the problem. This suppresses the display of module names.
This also completely fixes the problem with display of `AGray32`. (It was accidentally half-fixed in PR #199.)
```julia
julia> import ColorTypes # not `using`
julia> ColorTypes.RGB[] # v0.10.0
0-element Array{ColorTypes.RGB,1} with eltype ColorTypes.RGB
julia> ColorTypes.RGB24[] # v0.10.6
0-element Array{ColorTypes.RGB24,1} with eltype ColorTypes.RGB24
julia> ColorTypes.RGB24[] # this PR
0-element Array{RGB24,1} with eltype ColorTypes.RGB24
```
```julia
julia> AGray32(1) # v0.10.0 or earlier
AGray32{N0f8}(1.0,1.0)
julia> AGray32(1) # v0.10.6 Damn!
AGray32(1.0,1.0)
julia> AGray32(1) # this PR …
```

Suppress display of module names for invisible types

---

src/traits.jl

I'm guessing the old implementation predated Julia 0.6 and the new type system.

Simplify the implementation of eltype

---

test/show.jl

Aside from the monthly UnitTest action, perhaps PkgEval will start to fail. :confused:
Shall we release ColorTypes v0.10.9?

Fix tests for printing on nightly

---

src/operations.jl
src/precompile.jl

This yields a 3x speed improvement in `rand(RGB{Float32}, sz)` on Julia 1.6:
Before:
```julia
julia> @time rand(RGB{Float32}, (1000, 1000, 10));
0.387576 seconds (2 allocations: 114.441 MiB)
```
After:
```julia
julia> @time rand(RGB{Float32}, (1000, 1000, 10));
0.125350 seconds (2 allocations: 114.441 MiB)
```
For the precompiles, some of these take >60ms to infer, so it's nice to get them cached.

Improve `rand` speed and add some additional precompiles

---

test/operations.jl

Theoretically, there is still a chance of unintentional success, but the probability is small enough.
```julia
julia> rand(Gray{Q3f12})  # returns a negative value about 50% of the time.
Gray{Q3f12}(-0.3162Q3f12)
```
Fixes #225

Fix "broken" test which may succeed unintentionally

---

src/traits.jl
test/traits.jl

cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/186#issuecomment-672044220
This would qualify as part of v0.10.x, but in downstream packages, the benefits of the generalization would have to wait until v0.11.0. I'm submitting this PR now because I'm assuming we'll be moving the comparison methods to "operations.jl" or "comparisons.jl" (or something). In other words, this is a decluttering before the move.

Generalize `==`

---

Project.toml

This is the last checkpoint for the release of ColorTypes v0.11. (I think I've declared something similar in the past. :sweat_smile:)
The following is the correspondence between the versions I had assumed.
|ColorTypes      | v0.10.10 | v0.11.0 (#213, #186?) | v0.12.0 (#177, #206, #222, #197?)|
|:---------------|:---------|:----------------------|:--------|
|Colors          |(v0.12.6) | v0.12.7               | v0.13.0 |
|ColorVectorSpace|(v0.9.1)  | v0.9.2                | v0.9.3  |
The important thing is that #222 will break a lot of doctests, so have it guarded by Colors.jl's cap. So I am concerned about the end of ColorTypes v0.11, i.e. the start of ColorTypes v0.12. (https://github.com/JuliaGraphics/ColorTypes.jl/pull/213#issuecomment-673599021)
There is room for debate as to what to …

Version 0.10.10

---

Project.toml
src/precompile.jl

The bit rot in this package itself should be detected by testing with Julia v1.7.0-DEV.694 or later.
This is an alternative to PR #232.

Remove assertions in "src/precompile.jl"

---

Project.toml
src/traits.jl

I am not fully aware of this inference issue, but v0.10.11 affects the testing of ImageCore.jl, so I am releasing this as a quick fix.

Fix inference regression on `eltypes_supported`

---

src/ColorTypes.jl
src/traits.jl
test/traits.jl

Note: this replaces #186 for `<`. I'll add the rest in separate PRs.
#160 "moved" isless from ColorVectorSpace to ColorTypes, but didn't likewise move <. Because < falls back to isless,
this meant that comparisons like Gray(0.3) < Gray(NaN) returned a different answer than 0.3 < NaN.
This is breaking, because moving methods from one package to another is breaking unless all compatible versions of the "upstream" package (ColorVectorSpace) were designed with the possibility that these methods would be present in this package. That's not the case, so we need to introduce an incompatibility. Worth nothing that if we put ColorTypes, Colors, and ColorVectorSpace into a single multi-package repository, we might be able to such a transfer in a non-breaking way.

Implement `<` in addition to `isless`

---

test/conversions.jl
test/customtypes.jl
test/traits.jl
test/types.jl

This includes the tests for PR #177.
This also includes tests for issue #230. However, I have not added tests for comparison with real numbers, as that is controversial (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/230#issuecomment-801010654).

Add tests for constructors of `TransparentGray` and custom types

---

src/error_hints.jl
src/traits.jl
test/customtypes.jl
test/error_hints.jl
test/traits.jl

This is a part of PR #186.
This moves the `zero` and `oneunit` for  some of grays and rgbs that were defined in ColorVectorSpace to ColorTypes. (That is, this is a breaking change.)
For `zero`, a color with all components zero is considered reasonable as an additive identity in most color spaces. On the other hand, it is difficult to define `oneunit` in general. Therefore, `oneunit` is defined only for specific color spaces.
This does not change the definition of `one`.
Fixes #219

Add `zero` & `oneunit` for more types

---

src/error_hints.jl
test/error_hints.jl

This PR was separated from PR #186 via PR #243.
I changed the condition to suggest new multiplication operators to exclude real scaling cases like `RGB(1,1,1) * 0.3` in this PR.

Add error hints for color arithmetic

---

src/ColorTypes.jl
src/traits.jl
test/traits.jl

This also generalizes `nan` to support any `Colorant` type. Note that this does not export `nan` to prevent name clashes.
see also: https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/75

Move `isfinite`, `isinf`, `isnan`, and `nan` from ColorVectorSpace

---

src/ColorTypes.jl
src/conversions.jl
test/conversions.jl

In practice, the method does not have much impact because of the fallback in `Base`. However, there are some differences as follows:
```julia
julia> real(Gray{Float32})
Float32
julia> real(Gray24)
ERROR: MethodError: no method matching zero(::Type{Gray24})
julia> real(Gray)
N0f8 (alias for Normed{UInt8, 8})
```
```julia
julia> real(Gray{Float32})
Float32
julia> real(Gray24)
N0f8 (alias for Normed{UInt8, 8})
julia> real(Gray)
ERROR: MethodError: no method matching zero(::Type{Any})
```

Move `real(::Type{<:AbstractGray})` from ColorVectorSpace

---

Project.toml

- cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/158#discussion_r376705144
- cf. issue #235
Optional
- They are not related to vector representations.
- cf. https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/75
I'm changing my mind on the policy of postponing PR #243 to ColorTypes v0.12 and releasing the corresponding ColorVectorSpace v0.10. I would like to proceed to ColorTypes v0.12.0 without releasing v0.11.x if possible.
|ColorTypes      | v0.10.10+| v0.11.0 | v0.12.0 |
|:---------------|:---------|:--------|:--------|
|Colors          |(v0.12.6+)| v0.12.8 | v0.13.0 |
|ColorVectorSpace|(v0.9.1+) | v0.9.4  |*v0.10.0*|

Version 0.11.0

---

src/traits.jl
test/customtypes.jl
test/show.jl
test/traits.jl

Since only `AGray32` and `ARGB32` are defined as non-parametric `TransparentColor` types, I did not notice this problem, but it would be better to specialize `compN` for `ColorAlpha` as well as `AlphaColor`.
This is not an urgent issue, since it can be solved by overloading `compN` by users or packages which define custom color types. Therefore, I will make this a part of v0.12 instead of v0.11, even though this is a non-breaking change as long as `alpha(c)` works.

Improve `compN` for non-parametric `ColorAlpha` types

---

src/show.jl
src/traits.jl
test/show.jl

Fixes #202, Fixes #191 ~(and https://github.com/JuliaGraphics/ColorTypes.jl/issues/179#issuecomment-617131514)~
This simplifies the display of array elements based on the `:typeinfo` property. This also simplifies the display of color components by setting the `:typeinfo` property.
This prints the elements of gray arrays as real numbers.

Simplify display of colors and arrays of colors

---

src/ColorTypes.jl
src/error_hints.jl
src/traits.jl
test/error_hints.jl
test/operations.jl
test/traits.jl

This defines `one` as a real (i.e. dimensionless) number `１`.
I am not convinced that this is the best way, but I think this is a reasonable option.
Since this does not support `ones(ARGB, ...)` and so on, this may requires PR #177 ~as a part of v0.11.0~
Closes #235, #137

[RFC] (Re-)define `one` for `Colorant`

---

src/traits.jl
src/types.jl
test/conversions.jl
test/traits.jl
test/types.jl

Closes #162. I decided to continue to support any `::Number` as long as it can be `convert`ed to a supported type. Consequently
```julia
julia> using FixedPointNumbers, ColorTypes
julia> FixedPointNumbers.floattype(::Type{Complex{T}}) where T = Complex{floattype(T)}
julia> gray(1+0im)
1.0N0f8
julia> gray(1+1im)
ERROR: InexactError: Int64(1 + 1im)
Stacktrace:
[1] Real at ./complex.jl:37 [inlined]
[2] convert at ./number.jl:7 [inlined]
[3] FixedPoint at /home/tim/.julia/packages/FixedPointNumbers/w2pxG/src/FixedPointNumbers.jl:56 [inlined]
[4] convert at ./number.jl:7 [inlined]
[5] gray(::Complex{Int64}) at /home/tim/.julia/dev/ColorTypes/src/traits.jl:37
[6] top-level scope at REPL[5]:1
```
(Not sure if that is worth adding to the tests.) This is consistent with the general philosophy that …

Support alpha(::Number) and ensure alpha/gray return compatible types

---

src/ColorTypes.jl
src/conversions.jl
src/traits.jl
src/types.jl
test/operations.jl
test/traits.jl

This classifies the properties of real numbers and the properties of the black-gray-white colors.
This should be mostly compatible for a single specific method, but may affect the multiple dispatch or ambiguity.
README.md will be updated with PR #250.
Closes #230

Make `AbstractGray` an abstract type instead of an alias

---

src/conversions.jl
src/types.jl
test/conversions.jl

Closes #242
```
julia> RGB(255, 0, 0) # This PR
ERROR: ArgumentError: The components of RGB are normalized to the range 0-1,
but (255, 0, 0) are integers in the range 0-255.
Consider dividing your input values by 255, for example: RGB{N0f8}(255/255, 0/255, 0/255)
The component type N0f8 is an 8-bit type representing 256 values from 0 to 1.
You can also use `reinterpret(N0f8, x % UInt8)` to encode the input into N0f8.
See the READMEs for FixedPointNumbers and ColorTypes for more information.
```

Modify error messages in constructors

---

src/types.jl
test/runtests.jl

`eltype_ub` did not necessarily return the actual upper bound. (cf. `eltypes_supported`)
Algorithms based on `eltype_default` are recommended over `eltype_ub`. (cf. issue #257)
This also removes `ColorTypes.ctypes`.

Remove `eltype_ub`

---

README.md
src/conversions.jl
src/traits.jl
src/types.jl
test/customtypes.jl
test/types.jl

This eliminates the macro-based constructor generation. This helps add user-defined types (cf. #179).
This also allows grays to be used in the constructor argument in more cases (cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/177#discussion_r412868245).
Fixes #156

[RFC] Redesign color constructors

---

src/operations.jl
test/operations.jl

This also makes it possible to omit specifying the `init` value.
```julia
julia> rgb = rand(RGB, 1000, 1000);
julia> @btime reducec.(+, 0.2, rgb); # conventional
1.746 ms (6 allocations: 7.63 MiB)
julia> @btime reducec.(+, rgb, init=0.2); # with `init`
1.897 ms (13 allocations: 7.63 MiB)
julia> @btime reducec.(+, rgb); # omitting `init` (=`0.0`)
1.883 ms (5 allocations: 7.63 MiB)
```
Closes #247

Add `init` keyword support for `reducec` & `mapreducec`

---

src/conversions.jl
test/conversions.jl

This supports adding/stripping alpha for colors other than `Color3`.
Fixes #241

Generalize conversions within the same base color

---

src/operations.jl
src/traits.jl
src/types.jl

PR #197 made it unnecessary to use `base_colorant_type` (via `mapc`) in some cases.
This does not help to improve run-time performance, though.

Simplify the 0-arg constructor and constructor-like functions

---

Project.toml
src/operations.jl
test/operations.jl

Formerly we fell back to `==`, but this does not do the right thing
for `NaN` components.

Support `isequal`

---

Project.toml
src/operations.jl
test/operations.jl

Formerly we fell back to `==`, but this does not do the right thing
for `NaN` components.
(cherry picked from commit b8ed378531f1445ed2402a00d49ecbf64ce5a0fc)
Backported to the release-0.11 branch.

Support `isequal` (#272)

---

Project.toml

To avoid unexpected version bump such as #273

ColorTypes v0.12.0-dev

---

Project.toml

Instead of reverting the commits in master branch (#274), this PR simply bump a patch version in `release-0.11` branch.

ColorTypes v0.11.2

---

README.md
src/ColorTypes.jl
src/operations.jl
src/traits.jl
src/types.jl
test/operations.jl
test/runtests.jl
test/traits.jl
test/types.jl

Similar to pull request #271 using the terminology of CSS instead and including some tests.
As far as I can tell, I implemented everything needed. The `gamutmin` and `gamutmax` are from the CSS recommendation, but I'm not 100% certain it stays within the sRGB gamut, rather likely it does not.

Add Oklab and Oklch

---

Project.toml
ext/StyledStringsExt.jl

This enables easy interoperability with the Face constructor of StyledStrings.
With this, it's easy to do fun things like:

Support conversion to a StyledStrings.SimpleColor

---

test/operations.jl

We do not have a way to obtain a stable multi-dimensional array of random numbers. That situation does not change with `StableRNGs`.
I think it is sufficient here just to make sure that the API works.

Fix unstable `rand` tests

---

.github/workflows/UnitTest.yml

https://github.com/JuliaGraphics/ColorTypes.jl/pull/305#issuecomment-2081372732
Considering the backport, it would have been nice if this had been done with PR #301, but the timing was not clearly announced, so there was no choice.

Update macOS test targets

---

Project.toml
test/Project.toml
test/runtests.jl

Now that StyledStrings is registered, we can do away with this code (and also include StyledStrings support in a release, which would be nice).

Remove redundant pre-register StyledStrings compat

---

src/ColorTypes.jl

This should hopefully help remove warnings across the ecosystem. Discussion in https://github.com/JuliaIO/ImageMagick.jl/issues/235
This should lead to a bump in the version since it could be breaking.
cc @dgleich @ararslan

Remove deprecated bindings in ColorTypes.jl
