JuliaGraphics/ColorTypes.jl

- README.md
> Include tips in the README for adding new colorspaces

- src/traits.jl
See https://github.com/timholy/Images.jl/issues/351
> Speed up base_colorant_type on julia 0.3

- .travis.yml
- src/ColorTypes.jl
- src/traits.jl
And enable 0.3 and 0.4 on Travis
> Union() -> Union{}

- src/types.jl
- test/runtests.jl
See https://github.com/JuliaGraphics/ColorTypes.jl/issues/16
> Make types explicit in macro call

- .travis.yml
- REQUIRE
- src/ColorTypes.jl
- src/show.jl
- src/traits.jl
- src/types.jl
- test/runtests.jl
Incorporate and fix deprecations caused by the wonderful https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/27. This also commits to julia 0.4 and deletes cruft.
> Ufixed->UFixed and commit to julia 0.4

- src/traits.jl
- src/types.jl
Images tests have been failing lately on julia-0.5, hopefully this is one step along the way to fixing them.
> Fixes for julia-0.5

- src/ColorTypes.jl
- src/operations.jl
- test/runtests.jl
Moved from https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/46.
> Generate random RGB/Gray arrays

- src/conversions.jl
- test/runtests.jl
> Add alpha parameter to alphacolor

- src/traits.jl
- test/runtests.jl
> equal for transparent colors

- README.md
- src/operations.jl
- test/runtests.jl
Ref https://github.com/JuliaGraphics/Colors.jl/pull/253#issuecomment-249902760
> Fix mapc on non-RGB transparent Color{T,3}

- src/operations.jl
- test/runtests.jl
Also check that comparing equality among hashes gives the same result as testing equality.
> Support hashing colors

- .travis.yml
- REQUIRE
- src/ColorTypes.jl
- src/operations.jl
- src/show.jl
- src/traits.jl
- src/types.jl
- test/runtests.jl
Also bumps julia to a minimum version of 0.5, since 0.4 is getting increasingly hard to support.
> Update for name changes in FixedPointNumbers

- src/ColorTypes.jl
- src/conversions.jl
- src/show.jl
- src/traits.jl
- src/types.jl
- test/runtests.jl
Won't pass until https://github.com/JuliaLang/Compat.jl/pull/320 merges and tags. ~~Doesn't fix https://github.com/JuliaGraphics/ColorTypes.jl/pull/68#discussion_r99741490. Most other issues with #68 seem fixed, but see a specific comment below.~~
> Fix some breakages in #68

- REQUIRE
- src/types.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
> Fix 0.6 abstract type declaration depwarn

- src/ColorTypes.jl
- src/conversions.jl
- src/operations.jl
- src/traits.jl
- src/types.jl
- test/runtests.jl
See https://github.com/JuliaGraphics/ColorTypes.jl/pull/81#issuecomment-294139027. I added some tests to make sure the behavior we were trying to avoid doesn't get re-added.
> Remove old deprecations

- .travis.yml
- src/operations.jl
- test/runtests.jl
Fixes ambiguities that have cropped up on recent versions of 0.6.
> Fix and test for ambiguities

- .travis.yml
- REQUIRE
- src/types.jl
> fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

- src/conversions.jl
- src/traits.jl
- test/runtests.jl
These were discovered in the course of working on porting ColorVectorSpace.
> Fix a couple more 0.7 issues

- src/types.jl
- test/runtests.jl
Fixes https://github.com/JuliaImages/Images.jl/issues/750. CC @bjarthur
> Allow construction of RGB from grayscale entries

- .gitignore
- .travis.yml
- Project.toml
- REQUIRE
it's time to move to the new Registrator 😄
> add Project.toml and drop 0.7 support

- Project.toml
To silence the emails from CompatHelper!
> Fix compat section of Project.toml

- .travis.yml
This fixes #138, and updates the target of stable release versions (Julia v1.1 -> v1.3).
> Update ".travis.yml" to run `Codecov.submit` (Fixes #138)

- Project.toml
Curiously, CompatHelper didn't seem to run on this one. CC @DilumAluthge
> Bump Compat for FixedPointNumbers

- test/conversions.jl
- test/operations.jl
- test/runtests.jl
- test/show.jl
- test/traits.jl
- test/types.jl
This PR splits the tests into multiple files and adds `@testset`s and some extra tests. (Fixes #149)
I noticed some issues (cf. #151, #152, #153, #154, #156, #157), but this PR does not make any changes in "src".
To make it easier to track test cases, I created commits in small increments. Once confirmed, you can squash the commits.
This PR still leaves the inconsistencies in the test cases and notations. However, this PR may help a little to know the inconsistencies and understand where we need to fix.
> Organize test cases (Fixes #149)

- src/types.jl
- test/types.jl
> Fix ABGR/BGRA constructors with integer arguments (Fixes #157)

- Project.toml
- src/traits.jl
- test/show.jl
This also modifies the test for Julia nightly build.
> Version 0.10.6

- src/traits.jl
- test/traits.jl
This makes sure that `_parameter upper_bound` is used with `TransparentColor`, not its subtypes.
This also changes the implementation of `eltypes_supported`.
Closes #208
> Make use of `_parameter_upper_bound` safer

- src/precompile.jl
These precompiles help ImageCore precompile other MethodInstances.
> Add a few more precompiles

- src/traits.jl
The recursion mechanism using `supertype` could be broken when a subtype of `TransparentColor` was added. Therefore, the checking with `nameof` was used for safety in PR #211.
However, it interfered with constant folding. This avoids the use of `nameof` for the checking.
Closes #208
> Fix regression of constant propagation in `color_type`

- test/customtypes.jl
- test/operations.jl
- test/show.jl
- test/traits.jl
- test/types.jl
This is one of the preparations for v0.12, using the time to conclude on the changes in v0.11.
> Modularize custom type definitions for testing

- src/ColorTypes.jl
- src/operations.jl
- test/operations.jl
This is a proposal to drastically change the implementation of `rand`. (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/150#issuecomment-594986636)
> [RFC] Use sampler-based Random API

- src/operations.jl
- test/operations.jl
> Update `gamutmin`/`gamutmax` based on sRGB gamut

- src/conversions.jl
- test/conversions.jl
This is a preparation for PR #197.
> Generalize conversions from/to `Real`

- src/conversions.jl
- src/operations.jl
- src/show.jl
- test/operations.jl
This adds a component iterator as a "private" API.
This re-implements the folding functions with the iterator.
cf. #190, #247
> Add component iterator

- src/operations.jl
- test/operations.jl
This will be useful for supporting `clamp`
> Implement 3-colorant `mapc`

- src/operations.jl
- test/operations.jl
> add missing Gray{Bool} support for rand

- .github/workflows/TagBot.yml
- Project.toml
- README.md
- ext/StyledStringsExt.jl
- src/ColorTypes.jl
- src/operations.jl
- src/traits.jl
- src/types.jl
- test/conversions.jl
- test/operations.jl
- test/runtests.jl
- test/traits.jl
- test/types.jl
It's been more than a year since the last release. I've pulled commits since then into the v0.11 backport branch.
Looks like CI isn't running automatically - does a committer need to trigger the tests?
> Backport recent commits to v0.11

- .github/dependabot.yml
- .github/workflows/CompatHelper.yml
- .github/workflows/UnitTest.yml
- .github/workflows/UnitTestArm.yml
cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/301#issuecomment-2077022254
> Backport "Update workflows (#301)”

- Project.toml
- test/Project.toml
- test/runtests.jl
I do not understand the need for me to create this PR, but this PR itself might be necessary for sound development.
> Add test and followup for `StyledStringsExt`
